name: Deploy React Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: my-project
  SERVICE: react-frontend
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create ENV
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> .env.production
          echo "VITE_AUTH_URL=${{ secrets.VITE_AUTH_URL }}" >> .env.production

      - run: npm install
      - run: npm run build -- --mode production

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - uses: google-github-actions/setup-gcloud@v2

      - run: |
          gcloud builds submit --tag gcr.io/$PROJECT_ID/$SERVICE

      - run: |
          gcloud run deploy $SERVICE \
          --image gcr.io/$PROJECT_ID/$SERVICE \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated